steps:
- name: 'gcr.io/k8s-skaffold/pack'
  entrypoint: 'pack'
  args: ['build', '--builder=gcr.io/buildpacks/builder', '--publish', 'asia-northeast3-docker.pkg.dev/handy-empire-393206/bdpr-docker-repo/bdpr:v1']
